/* 
 * File:   main.cpp
 * Author: damien
 *
 * Created on November 27, 2012, 2:40 PM
 */

#include <cstdlib>
#include <stdio.h>
#include "soapBankProxy.h"
#include "Bank.nsmap"
#include "account.h"
#include "clientinstance.h"

//#include "account.h" // generated by gSOAP compiler

using namespace std;

/*
 * 
 */
int main(int argc, char** argv) {
    
    clientinstance currentclient;
    currentclient.init();
    

    int action;
    currentclient.menu();
    
    while(true) 
    {
        scanf("%d", &action);
        
        switch(action)
        {
                case 1:
                    currentclient.performdeposit();
                    break;
                case 2:
                    currentclient.performwithdraw();
                    break;
                case 3:
                    currentclient.performtransfert();
                    break;
                case 4:
                    currentclient.getbalance();
                    break;
                case 5:
                    currentclient.switchaccount();
                    break;
        }
                    
      currentclient.menu();
    }
    return 0;
}

