/* soapBankService.cpp
   Generated by gSOAP 2.8.11 from service.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapBankService.h"

BankService::BankService()
{	BankService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

BankService::BankService(const struct soap &_soap) : soap(_soap)
{ }

BankService::BankService(soap_mode iomode)
{	BankService_init(iomode, iomode);
}

BankService::BankService(soap_mode imode, soap_mode omode)
{	BankService_init(imode, omode);
}

BankService::~BankService()
{ }

void BankService::BankService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns", "urn:Account", NULL, NULL},
	{"ns1", "urn:Bank", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
};

void BankService::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void BankService::reset()
{	destroy();
	soap_done(this);
	soap_init(this);
	BankService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

#ifndef WITH_PURE_VIRTUAL
BankService *BankService::copy()
{	BankService *dup = SOAP_NEW_COPY(BankService(*(struct soap*)this));
	return dup;
}
#endif

int BankService::soap_close_socket()
{	return soap_closesock(this);
}

int BankService::soap_force_close_socket()
{	return soap_force_closesock(this);
}

int BankService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this, string, detailXML);
}

int BankService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this, subcodeQName, string, detailXML);
}

int BankService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this, string, detailXML);
}

int BankService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this, subcodeQName, string, detailXML);
}

void BankService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void BankService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *BankService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

void BankService::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *BankService::soap_header()
{	return this->header;
}

int BankService::run(int port)
{	if (soap_valid_socket(this->master) || soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()) || serve())
				return this->error;
			soap_destroy(this);
			soap_end(this);
		}
	}
	else
		return this->error;
	return SOAP_OK;
}

SOAP_SOCKET BankService::bind(const char *host, int port, int backlog)
{	return soap_bind(this, host, port, backlog);
}

SOAP_SOCKET BankService::accept()
{	return soap_accept(this);
}

#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
int BankService::ssl_accept()
{	return soap_ssl_accept(this);
}
#endif

int BankService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->max_keep_alive;
#endif
	do
	{

#ifndef WITH_FASTCGI
		if (this->max_keep_alive > 0 && !--k)
			this->keep_alive = 0;
#endif

		if (soap_begin_serve(this))
		{	if (this->error >= SOAP_STOP)
				continue;
			return this->error;
		}
		if (dispatch() || (this->fserveloop && this->fserveloop(this)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this);
#else
			return soap_send_fault(this);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this);
		soap_end(this);
	} while (1);
#else
	} while (this->keep_alive);
#endif
	return SOAP_OK;
}

static int serve_ns1__Deposit(BankService*);
static int serve_ns1__Withdraw(BankService*);
static int serve_ns1__initAccounts(BankService*);
static int serve_ns1__Transfert(BankService*);
static int serve_ns1__SwitchAccount(BankService*);
static int serve_ns1__GetState(BankService*);

int BankService::dispatch()
{	soap_peek_element(this);
	if (!soap_match_tag(this, this->tag, "ns1:Deposit"))
		return serve_ns1__Deposit(this);
	if (!soap_match_tag(this, this->tag, "ns1:Withdraw"))
		return serve_ns1__Withdraw(this);
	if (!soap_match_tag(this, this->tag, "ns1:initAccounts"))
		return serve_ns1__initAccounts(this);
	if (!soap_match_tag(this, this->tag, "ns1:Transfert"))
		return serve_ns1__Transfert(this);
	if (!soap_match_tag(this, this->tag, "ns1:SwitchAccount"))
		return serve_ns1__SwitchAccount(this);
	if (!soap_match_tag(this, this->tag, "ns1:GetState"))
		return serve_ns1__GetState(this);
	return this->error = SOAP_NO_METHOD;
}

static int serve_ns1__Deposit(BankService *soap)
{	struct ns1__Deposit soap_tmp_ns1__Deposit;
	struct ns1__DepositResponse soap_tmp_ns1__DepositResponse;
	char * soap_tmp_string;
	soap_default_ns1__DepositResponse(soap, &soap_tmp_ns1__DepositResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__DepositResponse.rresult = &soap_tmp_string;
	soap_default_ns1__Deposit(soap, &soap_tmp_ns1__Deposit);
	soap->encodingStyle = "";
	if (!soap_get_ns1__Deposit(soap, &soap_tmp_ns1__Deposit, "ns1:Deposit", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->Deposit(soap_tmp_ns1__Deposit.entry, soap_tmp_ns1__DepositResponse.rresult);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__DepositResponse(soap, &soap_tmp_ns1__DepositResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__DepositResponse(soap, &soap_tmp_ns1__DepositResponse, "ns1:DepositResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__DepositResponse(soap, &soap_tmp_ns1__DepositResponse, "ns1:DepositResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_ns1__Withdraw(BankService *soap)
{	struct ns1__Withdraw soap_tmp_ns1__Withdraw;
	struct ns1__WithdrawResponse soap_tmp_ns1__WithdrawResponse;
	char * soap_tmp_string;
	soap_default_ns1__WithdrawResponse(soap, &soap_tmp_ns1__WithdrawResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__WithdrawResponse.rresult = &soap_tmp_string;
	soap_default_ns1__Withdraw(soap, &soap_tmp_ns1__Withdraw);
	soap->encodingStyle = "";
	if (!soap_get_ns1__Withdraw(soap, &soap_tmp_ns1__Withdraw, "ns1:Withdraw", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->Withdraw(soap_tmp_ns1__Withdraw.entry, soap_tmp_ns1__WithdrawResponse.rresult);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__WithdrawResponse(soap, &soap_tmp_ns1__WithdrawResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__WithdrawResponse(soap, &soap_tmp_ns1__WithdrawResponse, "ns1:WithdrawResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__WithdrawResponse(soap, &soap_tmp_ns1__WithdrawResponse, "ns1:WithdrawResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_ns1__initAccounts(BankService *soap)
{	struct ns1__initAccounts soap_tmp_ns1__initAccounts;
	struct ns1__initAccountsResponse soap_tmp_ns1__initAccountsResponse;
	char * soap_tmp_string;
	soap_default_ns1__initAccountsResponse(soap, &soap_tmp_ns1__initAccountsResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__initAccountsResponse.rresult = &soap_tmp_string;
	soap_default_ns1__initAccounts(soap, &soap_tmp_ns1__initAccounts);
	soap->encodingStyle = "";
	if (!soap_get_ns1__initAccounts(soap, &soap_tmp_ns1__initAccounts, "ns1:initAccounts", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->initAccounts(soap_tmp_ns1__initAccounts.bankid, soap_tmp_ns1__initAccountsResponse.rresult);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__initAccountsResponse(soap, &soap_tmp_ns1__initAccountsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__initAccountsResponse(soap, &soap_tmp_ns1__initAccountsResponse, "ns1:initAccountsResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__initAccountsResponse(soap, &soap_tmp_ns1__initAccountsResponse, "ns1:initAccountsResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_ns1__Transfert(BankService *soap)
{	struct ns1__Transfert soap_tmp_ns1__Transfert;
	struct ns1__TransfertResponse soap_tmp_ns1__TransfertResponse;
	char * soap_tmp_string;
	soap_default_ns1__TransfertResponse(soap, &soap_tmp_ns1__TransfertResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__TransfertResponse.rresult = &soap_tmp_string;
	soap_default_ns1__Transfert(soap, &soap_tmp_ns1__Transfert);
	soap->encodingStyle = "";
	if (!soap_get_ns1__Transfert(soap, &soap_tmp_ns1__Transfert, "ns1:Transfert", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->Transfert(soap_tmp_ns1__Transfert.entry, soap_tmp_ns1__Transfert.accountid, soap_tmp_ns1__TransfertResponse.rresult);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__TransfertResponse(soap, &soap_tmp_ns1__TransfertResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__TransfertResponse(soap, &soap_tmp_ns1__TransfertResponse, "ns1:TransfertResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__TransfertResponse(soap, &soap_tmp_ns1__TransfertResponse, "ns1:TransfertResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_ns1__SwitchAccount(BankService *soap)
{	struct ns1__SwitchAccount soap_tmp_ns1__SwitchAccount;
	struct ns1__SwitchAccountResponse soap_tmp_ns1__SwitchAccountResponse;
	char * soap_tmp_string;
	soap_default_ns1__SwitchAccountResponse(soap, &soap_tmp_ns1__SwitchAccountResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__SwitchAccountResponse.rresult = &soap_tmp_string;
	soap_default_ns1__SwitchAccount(soap, &soap_tmp_ns1__SwitchAccount);
	soap->encodingStyle = "";
	if (!soap_get_ns1__SwitchAccount(soap, &soap_tmp_ns1__SwitchAccount, "ns1:SwitchAccount", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->SwitchAccount(soap_tmp_ns1__SwitchAccount.bankid, soap_tmp_ns1__SwitchAccountResponse.rresult);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__SwitchAccountResponse(soap, &soap_tmp_ns1__SwitchAccountResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__SwitchAccountResponse(soap, &soap_tmp_ns1__SwitchAccountResponse, "ns1:SwitchAccountResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__SwitchAccountResponse(soap, &soap_tmp_ns1__SwitchAccountResponse, "ns1:SwitchAccountResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve_ns1__GetState(BankService *soap)
{	struct ns1__GetState soap_tmp_ns1__GetState;
	struct ns1__GetStateResponse soap_tmp_ns1__GetStateResponse;
	char * soap_tmp_string;
	soap_default_ns1__GetStateResponse(soap, &soap_tmp_ns1__GetStateResponse);
	soap_tmp_string = NULL;
	soap_tmp_ns1__GetStateResponse.rresult = &soap_tmp_string;
	soap_default_ns1__GetState(soap, &soap_tmp_ns1__GetState);
	soap->encodingStyle = "";
	if (!soap_get_ns1__GetState(soap, &soap_tmp_ns1__GetState, "ns1:GetState", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->GetState(soap_tmp_ns1__GetStateResponse.rresult);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns1__GetStateResponse(soap, &soap_tmp_ns1__GetStateResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__GetStateResponse(soap, &soap_tmp_ns1__GetStateResponse, "ns1:GetStateResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__GetStateResponse(soap, &soap_tmp_ns1__GetStateResponse, "ns1:GetStateResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
